import { ArrowUpRight, Menu, X, ChevronDown, Orbit, Layers, Cpu, Radio, MoveUpRight } from 'lucide-react'
import { MobileNav } from '@/components/mobile-nav'

const current = [
  ['01', 'Smart Ride', 'A practical mobility platform exploring smarter, more accessible transport experiences.', 'ACTIVE PRODUCT'],
  ['02', 'NISMS', 'Digital systems that help organizations bring structure, visibility and intelligence to operations.', 'ACTIVE PRODUCT'],
  ['03', 'House For Rent', 'A focused property platform connecting people with clearer ways to find and manage housing.', 'ACTIVE PRODUCT'],
  ['04', 'Upcoming DISMs', 'A developing direction for digital information and management systems.', 'IN DEVELOPMENT'],
]
const concepts = [
  ['PRIZ~ON', 'Natural food & hospitality', 'A hospitality concept centered on organic food, waste reduction, local farmers and healthier sustainable living.'],
  ['ELON PROJECT', 'Solar-powered vehicles', 'An early sustainable mobility initiative exploring solar panels, batteries and lower-emission transport.'],
  ['LYN', 'African Union social platform', 'A pan-African platform concept for connection, culture, secure networking and digital independence.'],
  ['STATE SCHOOLS INTERNATIONAL', 'Future-oriented education', 'A learning concept focused on practical skills, creativity, technology, problem-solving and sustainability.'],
  ['AQUA NI', 'Modernized water transport', 'A concept for stronger, safer and lighter fiberglass boats for fishing, trade and tourism.'],
  ['NI SOCKET', 'EV charging & battery swap', 'A sustainable mobility infrastructure direction involving charging points and fast battery-swap hubs.'],
]

export default function Home() {
  return <main>
    <header className="fixed top-0 z-40 w-full border-b border-line/80 bg-background/90 backdrop-blur-md">
      <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10">
        <a href="#top" className="flex items-center gap-3" aria-label="Natural Intellects home"><img src="/asset-3.png" alt="Natural Intellects" className="h-10 w-auto object-contain" /><span className="hidden font-mono text-[10px] uppercase tracking-[.18em] text-muted sm:inline">N.I. / 2026</span></a>
        <nav className="hidden items-center gap-8 md:flex" aria-label="Primary navigation">{['About','Capabilities','Products','Innovation'].map((x)=><a key={x} href={'#'+x.toLowerCase()} className="font-mono text-[10px] uppercase tracking-widest text-muted hover:text-foreground">{x}</a>)}<a href="#contact" className="border border-foreground/50 px-4 py-3 font-mono text-[10px] uppercase tracking-widest hover:border-accent hover:text-accent">Start a conversation <ArrowUpRight className="ml-2 inline size-3" /></a></nav>
        <MobileNav />
      </div>
    </header>

    <section id="top" className="grid-lines relative flex min-h-[760px] items-end overflow-hidden border-b border-line px-6 pb-20 pt-40 lg:min-h-screen lg:px-10 lg:pb-24">
      <div className="pointer-events-none absolute right-[-8%] top-[18%] size-[560px] rounded-full border border-accent/50 lg:size-[760px]" /><div className="pointer-events-none absolute right-[11%] top-[34%] size-[250px] rounded-full border border-accent/25" />
      <div className="relative mx-auto w-full max-w-7xl"><div className="eyebrow mb-8 reveal">Uganda / Technology & Innovation</div><h1 className="max-w-5xl text-balance text-[clamp(3.8rem,10vw,9.8rem)] font-medium leading-[.88] tracking-[-.075em] reveal">Tech<br /><span className="text-accent">Over,</span> NI.</h1><div className="mt-14 flex max-w-2xl flex-col gap-8 border-t border-line pt-6 sm:flex-row sm:items-start sm:justify-between"><p className="max-w-sm text-pretty text-lg leading-relaxed text-muted">We build practical digital products today while keeping our eyes on the technologies that shape tomorrow.</p><a href="#about" className="group flex items-center gap-3 font-mono text-xs uppercase tracking-widest hover:text-accent">Explore the thinking <MoveUpRight className="size-4 group-hover:translate-x-1 group-hover:-translate-y-1" /></a></div></div>
    </section>

    <section id="about" className="mx-auto grid max-w-7xl gap-16 px-6 py-28 lg:grid-cols-[.75fr_1.25fr] lg:px-10 lg:py-40"><div><div className="eyebrow">01 / The company</div><h2 className="mt-8 max-w-sm text-4xl leading-tight tracking-[-.04em] lg:text-6xl">The ambition stayed. The path evolved.</h2></div><div className="max-w-2xl"><p className="text-2xl leading-snug text-foreground/90 lg:text-4xl">Natural Intellects is a Ugandan technology company building software, systems and digital products for the real world.</p><p className="mt-10 max-w-lg text-base leading-relaxed text-muted">We are not a web-design agency. We optimize what exists, transform how it works and invent what comes next. Our early explorations in sustainable transport and future-facing ideas now inform a sharper focus on useful, scalable digital solutions.</p></div></section>

    <section id="capabilities" className="border-y border-line bg-panel"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-32"><div className="mb-16 flex items-end justify-between"><div><div className="eyebrow">02 / What we do</div><h2 className="mt-6 text-4xl tracking-[-.05em] lg:text-7xl">Build with intent.</h2></div><div className="hidden font-mono text-xs text-muted md:block">[ CAPABILITIES / 04 ]</div></div><div className="grid gap-px border border-line bg-line md:grid-cols-2">{[['DIGITAL PRODUCTS','From first principle to useful interface.'],['BUSINESS SYSTEMS','Clarity and leverage for how organizations work.'],['SOFTWARE PLATFORMS','Durable foundations for ideas with room to grow.'],['TECHNOLOGY EXPLORATION','Research directions for a changing world.']].map(([a,b],i)=><div key={a} className="group bg-panel p-8 lg:p-12"><div className="mb-20 flex justify-between"><span className="font-mono text-xs text-accent">0{i+1}</span><ArrowUpRight className="size-5 text-muted group-hover:text-accent" /></div><h3 className="text-2xl tracking-[-.03em]">{a}</h3><p className="mt-3 max-w-xs leading-relaxed text-muted">{b}</p></div>)}</div></div></section>

    <section id="products" className="mx-auto max-w-7xl px-6 py-28 lg:px-10 lg:py-40"><div className="eyebrow">03 / Current portfolio</div><div className="mt-8 flex flex-col justify-between gap-8 border-b border-line pb-12 lg:flex-row lg:items-end"><h2 className="max-w-3xl text-5xl tracking-[-.06em] lg:text-8xl">Useful things,<br /><span className="text-muted">built forward.</span></h2><p className="max-w-xs text-sm leading-relaxed text-muted">The products below represent our current practical focus. Status is intentional.</p></div><div>{current.map(([n,name,desc,status])=><div key={name} className="group grid gap-5 border-b border-line py-8 md:grid-cols-[80px_1fr_1fr_180px] md:items-center"><span className="font-mono text-sm text-accent">{n}</span><h3 className="text-2xl tracking-tight group-hover:text-accent">{name}</h3><p className="max-w-md text-sm leading-relaxed text-muted">{desc}</p><span className="font-mono text-[10px] uppercase tracking-widest text-muted">{status}</span></div>)}</div></section>

    <section id="innovation" className="grid-lines border-y border-line bg-[#0d0e0e]"><div className="mx-auto max-w-7xl px-6 py-28 lg:px-10 lg:py-40"><div className="grid gap-16 lg:grid-cols-[.8fr_1.2fr]"><div><div className="eyebrow">04 / Innovation horizon</div><h2 className="mt-8 text-5xl tracking-[-.06em] lg:text-7xl">Beyond the<br /><span className="text-accent">obvious.</span></h2><p className="mt-8 max-w-sm text-sm leading-relaxed text-muted">These are concepts, research directions and future initiatives—not claims of deployed products. The horizon is part of the work.</p></div><div className="grid gap-px border border-line bg-line sm:grid-cols-2">{concepts.map(([name,sub,desc])=><article key={name} className="bg-background p-7"><Orbit className="mb-12 size-5 text-accent" /><div className="font-mono text-[10px] uppercase tracking-widest text-muted">Concept / R&D</div><h3 className="mt-4 text-xl tracking-tight">{name}</h3><p className="mt-2 text-xs uppercase tracking-wider text-accent-soft">{sub}</p><p className="mt-5 text-sm leading-relaxed text-muted">{desc}</p></article>)}</div></div></div></section>

    <section className="mx-auto max-w-7xl px-6 py-28 lg:px-10 lg:py-40"><div className="grid gap-16 lg:grid-cols-2"><div><div className="eyebrow">05 / Our philosophy</div><h2 className="mt-8 text-5xl tracking-[-.06em] lg:text-8xl">There&apos;s no<br /><span className="text-accent">Earth 2.</span></h2></div><div className="flex flex-col justify-end"><p className="text-2xl leading-snug lg:text-4xl">This is the constraint that makes us inventive. There is one home, one present, one chance to make what exists work better.</p><div className="mt-12 grid grid-cols-3 gap-4 border-t border-line pt-5 font-mono text-[10px] uppercase tracking-widest text-muted"><span>Optimize</span><span>Transform</span><span>Invent</span></div></div></div></section>

    <section id="contact" className="border-t border-line bg-accent px-6 py-24 text-background lg:px-10 lg:py-36"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-16 lg:flex-row lg:items-end"><div><div className="font-mono text-xs uppercase tracking-widest opacity-70">06 / Make something matter</div><h2 className="mt-8 max-w-3xl text-5xl font-medium tracking-[-.07em] lg:text-8xl">Let&apos;s build<br />what&apos;s next.</h2></div><a href="mailto:hello@naturalintellects.com" className="group flex items-center gap-4 border-b border-background/50 pb-3 text-lg hover:border-background">Start a conversation <ArrowUpRight className="size-5 group-hover:translate-x-1 group-hover:-translate-y-1" /></a></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-10 font-mono text-[10px] uppercase tracking-widest text-muted sm:flex-row sm:items-center sm:justify-between lg:px-10"><span>© 2026 Natural Intellects Ltd.</span><span>Uganda / Built with intent.</span><a href="#top" className="hover:text-accent">Back to top ↑</a></footer>
  </main>
}
