'use client'

import Link from 'next/link'
import { ArrowDown, ArrowUpRight, LockKeyhole, MessageCircle, ShieldCheck, UserRound } from 'lucide-react'
import { foundationProjects } from '@/data/foundation'

const deepPress = foundationProjects.deepPress
const helpAreas = [
  ['01', 'A place to start', 'When someone does not know how to begin, Deep Press could provide a conversational starting point.'],
  ['02', 'Putting things into words', 'Writing or talking through what is on someone’s mind may make it easier to articulate a difficult moment.'],
  ['03', 'Reflection', 'The experience is intended to create room for thoughtful reflection rather than simply generate responses.'],
  ['04', 'Supportive direction', 'Where appropriate, the concept could help someone consider a trusted person, a resource or another constructive next step.'],
  ['05', 'A bridge, not a replacement', 'Deep Press is exploring how technology might help someone move toward human or professional support—not replace it.'],
]

const journey = [
  ['Before the conversation', 'I do not know how to explain what I am feeling.'],
  ['Starting', 'I can at least put some of it into words.'],
  ['Reflection', 'Maybe I understand this difficult moment a little better.'],
  ['Next step', 'Maybe I know who or what I can reach out to.'],
]

function PulseVisual() {
  return <div className="relative flex min-h-[22rem] items-center justify-center overflow-hidden rounded-[2rem] border border-[var(--foundation-cyan)]/25 bg-[var(--foundation-primary)]/10" aria-label="A quiet point forming a supportive conversational connection" role="img"><div className="deep-press-wave absolute size-64 rounded-full border border-[var(--foundation-cyan)]/45" /><div className="deep-press-wave absolute size-40 rounded-full border border-[var(--foundation-yellow)]/45" /><div className="absolute left-[28%] top-[38%] size-3 rounded-full bg-[var(--foundation-cyan)] shadow-[0_0_28px_var(--foundation-cyan)]" /><div className="absolute right-[27%] bottom-[33%] size-3 rounded-full bg-[var(--foundation-orange)] shadow-[0_0_28px_var(--foundation-orange)]" /><div className="h-px w-[44%] rotate-[28deg] bg-gradient-to-r from-[var(--foundation-cyan)] via-[var(--foundation-yellow)] to-[var(--foundation-orange)]" /><div className="size-5 rounded-full bg-[var(--foundation-yellow)] shadow-[0_0_50px_var(--foundation-yellow)]" /><span className="absolute bottom-6 left-6 font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-surface)]/65">somewhere to begin</span></div>
}

export function DeepPressExperience() {
  return <main className="foundation-page min-h-screen overflow-hidden bg-[var(--foundation-background)] text-[var(--foundation-text)]"><header className="mx-auto flex max-w-screen-2xl items-center justify-between gap-6 px-6 py-5 lg:px-10"><Link href="/foundation" className="flex items-center gap-3"><img src="/foundation-logo.png" alt="Natural Intellects Foundation" className="h-14 w-auto object-contain" /><span className="hidden font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-muted)] sm:inline">/ {deepPress.name}</span></Link><Link href="/foundation#deep-press" className="font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-muted)] hover:text-[var(--foundation-orange)]">Back to Foundation <ArrowUpRight className="inline size-3" /></Link></header>
    <section className="mx-auto grid max-w-screen-2xl gap-12 px-6 pb-24 pt-16 lg:grid-cols-[1fr_.85fr] lg:items-center lg:px-10 lg:pb-32 lg:pt-28"><div><nav aria-label="Breadcrumb" className="mb-6 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-muted)]"><Link href="/foundation" className="hover:text-[var(--foundation-orange)]">Foundation</Link><span aria-hidden="true">/</span><span>Deep Press</span></nav><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-orange)]">{deepPress.name} / {deepPress.status}</div><h1 className="mt-6 max-w-4xl font-serif text-6xl leading-[.9] tracking-[-.07em] sm:text-8xl">Sometimes, the hardest part is finding somewhere to <em className="font-normal text-[var(--foundation-orange)]">start.</em></h1><p className="mt-8 max-w-2xl text-xl leading-8 text-[var(--foundation-muted)]">Deep Press explores how technology could provide an accessible space for people to express what they are experiencing, reflect, and find a path toward appropriate support.</p><div className="mt-10 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-muted)]"><span className="size-2 rounded-full bg-[var(--foundation-yellow)]" /> designed to explore, not to overclaim</div></div><PulseVisual /></section>
    <section id="why-it-matters" className="border-y border-[var(--foundation-text)]/15 bg-[var(--foundation-surface)] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-screen-2xl gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-orange)]">01 / Why it matters</div><h2 className="mt-5 max-w-md font-serif text-5xl leading-none tracking-[-.06em] sm:text-7xl">Difficult moments do not always come with clear words.</h2></div><div className="max-w-2xl"><p className="text-2xl leading-relaxed text-[var(--foundation-muted)]">People can experience distress, loneliness, uncertainty or overwhelm without knowing who to talk to, where to begin, or whether anyone will understand.</p><p className="mt-8 text-lg leading-8 text-[var(--foundation-muted)]">Stigma, isolation, uncertainty, lack of immediate access and the difficulty of starting a conversation can all add friction. Deep Press is being explored around that human problem.</p><div className="mt-12 grid gap-4 sm:grid-cols-2">{['How do I explain this?', 'Who could I talk to?', 'Where do I begin?', 'What could my next step be?'].map((item) => <div key={item} className="border-t border-[var(--foundation-text)]/20 pt-4 font-serif text-2xl">{item}</div>)}</div></div></div></section>
    <section id="first-step" className="mx-auto max-w-screen-2xl px-6 py-24 lg:px-10 lg:py-32"><div className="max-w-3xl"><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-orange)]">02 / The first step</div><h2 className="mt-5 font-serif text-5xl leading-none tracking-[-.06em] sm:text-7xl">Sometimes the first step is simply being able to say it.</h2></div><div className="mt-16 grid gap-3 sm:grid-cols-5">{['Thought', 'Words', 'Conversation', 'Reflection', 'Next step'].map((item, index) => <div key={item} className="foundation-path flex items-center gap-3 sm:block"><div className="flex size-16 items-center justify-center rounded-full border border-[var(--foundation-primary)] bg-[var(--foundation-surface)] font-serif text-lg text-[var(--foundation-primary)]">{index + 1}</div><div className="font-mono text-xs uppercase tracking-[.16em]">{item}</div>{index < 4 && <ArrowDown className="ml-auto size-4 text-[var(--foundation-orange)] sm:mx-auto sm:mt-5 sm:rotate-[-90deg]" />}</div>)}</div><p className="mt-12 max-w-2xl text-lg leading-8 text-[var(--foundation-muted)]">This is a conceptual representation of how a lower-friction digital conversation could help someone begin expressing what they are experiencing. It is not a clinical treatment pathway.</p></section>
    <section id="how-it-could-help" className="bg-[var(--foundation-text)] px-6 py-24 text-[var(--foundation-background)] lg:px-10 lg:py-32"><div className="mx-auto max-w-screen-2xl"><div className="max-w-3xl"><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-yellow)]">03 / How Deep Press could help</div><h2 className="mt-5 font-serif text-5xl leading-none tracking-[-.06em] sm:text-7xl">The person comes first. Technology is the means.</h2></div><div className="mt-16 border-t border-[var(--foundation-background)]/20">{helpAreas.map(([number, title, description]) => <article key={number} className="grid gap-4 border-b border-[var(--foundation-background)]/20 py-8 sm:grid-cols-[5rem_1fr_1.2fr] sm:items-start"><span className="font-mono text-xs text-[var(--foundation-yellow)]">{number}</span><h3 className="font-serif text-3xl font-normal">{title}</h3><p className="max-w-xl text-base leading-7 text-[var(--foundation-surface)]/75">{description}</p></article>)}</div></div></section>
    <section id="experience" className="mx-auto max-w-screen-2xl px-6 py-24 lg:px-10 lg:py-32"><div className="max-w-3xl"><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-orange)]">04 / The experience we are exploring</div><h2 className="mt-5 font-serif text-5xl leading-none tracking-[-.06em] sm:text-7xl">From “I do not know where to begin” to “at least I have somewhere to start.”</h2></div><div className="mt-16 grid gap-5 lg:grid-cols-4">{journey.map(([title, copy], index) => <article key={title} className="relative border-t border-[var(--foundation-text)]/25 pt-5"><span className="font-mono text-xs text-[var(--foundation-orange)]">0{index + 1}</span><h3 className="mt-8 font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-muted)]">{title}</h3><p className="mt-4 font-serif text-2xl leading-tight">{copy}</p>{index < 3 && <ArrowUpRight className="absolute right-2 top-5 hidden size-5 text-[var(--foundation-primary)] lg:block" />}</article>)}</div><p className="mt-12 font-mono text-[10px] uppercase tracking-[.16em] text-[var(--foundation-muted)]">Conceptual journey only — not a testimonial or promised outcome.</p></section>
    <section className="border-y border-[var(--foundation-text)]/15 bg-[var(--foundation-surface)] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-screen-2xl gap-12 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-orange)]">05 / Conversation → reflection → next step</div><h2 className="mt-5 max-w-2xl font-serif text-5xl leading-none tracking-[-.06em] sm:text-7xl">Could technology make it a little easier to take the next step?</h2><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--foundation-muted)]">A next step might involve reaching out to someone trusted, seeking professional support, finding an appropriate resource or taking another constructive action. Deep Press should never become a dead end.</p></div><div className="flex flex-col gap-3 font-mono text-xs uppercase tracking-[.16em]"><div className="rounded-full border border-[var(--foundation-primary)] px-6 py-5 text-center">Conversation</div><ArrowDown className="mx-auto size-4 text-[var(--foundation-orange)]" /><div className="rounded-full border border-[var(--foundation-primary)] px-6 py-5 text-center">Reflection</div><ArrowDown className="mx-auto size-4 text-[var(--foundation-orange)]" /><div className="rounded-full border border-[var(--foundation-primary)] bg-[var(--foundation-primary)] px-6 py-5 text-center text-[var(--foundation-background)]">Appropriate next step</div></div></div></section>
    <section id="responsibility" className="mx-auto max-w-screen-2xl px-6 py-24 lg:px-10 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-orange)]">06 / Responsible technology</div><h2 className="mt-5 max-w-md font-serif text-5xl leading-none tracking-[-.06em] sm:text-7xl">Supportive, never a substitute.</h2></div><div className="grid gap-5 sm:grid-cols-2"><article className="border-t border-[var(--foundation-text)]/20 pt-5"><ShieldCheck className="size-5 text-[var(--foundation-primary)]" /><h3 className="mt-6 font-serif text-2xl">Human support</h3><p className="mt-3 leading-7 text-[var(--foundation-muted)]">Deep Press is not a replacement for qualified mental-health professionals, emergency services or human relationships. Where someone may be in immediate danger, urgent human or emergency assistance is needed.</p></article><article className="border-t border-[var(--foundation-text)]/20 pt-5"><LockKeyhole className="size-5 text-[var(--foundation-primary)]" /><h3 className="mt-6 font-serif text-2xl">Privacy and dignity</h3><p className="mt-3 leading-7 text-[var(--foundation-muted)]">People should be able to approach difficult conversations with dignity. Privacy, data minimization and responsible handling of sensitive conversations are design principles—not claims of completed technical controls.</p></article><article className="border-t border-[var(--foundation-text)]/20 pt-5"><UserRound className="size-5 text-[var(--foundation-primary)]" /><h3 className="mt-6 font-serif text-2xl">Accessible starting point</h3><p className="mt-3 leading-7 text-[var(--foundation-muted)]">A digital conversation could offer a lower-friction place to begin for someone who does not yet know who to contact or what to say. It cannot solve every access-to-care barrier.</p></article><article className="border-t border-[var(--foundation-text)]/20 pt-5"><MessageCircle className="size-5 text-[var(--foundation-primary)]" /><h3 className="mt-6 font-serif text-2xl">Still being explored</h3><p className="mt-3 leading-7 text-[var(--foundation-muted)]">This is a concept and R&D direction. Its capabilities, boundaries and appropriate use must be developed responsibly with people at the center.</p></article></div></div></section>
    <section className="bg-[var(--foundation-text)] px-6 py-24 text-center text-[var(--foundation-background)] lg:px-10 lg:py-36"><div className="mx-auto max-w-4xl"><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-yellow)]">07 / Foundation philosophy</div><h2 className="mt-8 font-serif text-6xl leading-[.85] tracking-[-.08em] sm:text-9xl">One Life<br /><em className="font-normal text-[var(--foundation-yellow)]">at a Time.</em></h2><div className="mx-auto mt-12 grid max-w-2xl gap-3 font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-surface)]/70 sm:grid-cols-4">{['One person matters.', 'One conversation matters.', 'One opportunity to begin matters.', 'One next step matters.'].map((item) => <span key={item}>{item}</span>)}</div></div></section>
    <footer className="border-t border-[var(--foundation-text)]/15 px-6 py-10 lg:px-10"><div className="mx-auto flex max-w-screen-2xl flex-col justify-between gap-5 sm:flex-row"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-muted)]">Project status</div><div className="mt-2 font-serif text-2xl">Concept / R&D</div></div><Link href="/foundation" className="inline-flex items-center gap-2 self-start font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-muted)] hover:text-[var(--foundation-orange)]">Back to Foundation <ArrowUpRight className="size-3" /></Link></div></footer>
  </main>
}
