import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, BookOpen, ChevronRight } from 'lucide-react'
import { docsGroups, docSections } from '@/data/docs'

export function DocsShell({ children, activeSlug }: { children: React.ReactNode; activeSlug?: string }) {
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-line"><div className="mx-auto flex max-w-[1400px] items-center justify-between gap-6 px-5 py-5 lg:px-10"><Link href="/" className="font-mono text-xs uppercase tracking-[.22em]">Natural Intellects <span className="text-accent">/ Docs</span></Link><Link href="/" className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-muted hover:text-foreground"><ArrowLeft className="size-3" /> Back to site</Link></div></header><div className="mx-auto grid max-w-[1400px] gap-10 px-5 py-10 lg:grid-cols-[240px_minmax(0,760px)] lg:px-10 lg:py-16"><aside className="max-h-64 overflow-y-auto border-b border-line pb-6 lg:sticky lg:top-6 lg:max-h-none lg:overflow-visible lg:self-start lg:border-b-0 lg:pb-0"><div className="mb-6 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.2em] text-muted"><BookOpen className="size-4 text-accent" /> Documentation</div><nav aria-label="Documentation sections" className="grid gap-7">{docsGroups.map((group) => <div key={group}><div className="mb-3 font-mono text-[10px] uppercase tracking-[.16em] text-accent">{group}</div><div className="grid gap-2">{docSections.filter((doc) => doc.group === group).map((doc) => <Link key={doc.slug} href={`/docs/${doc.slug}`} aria-current={activeSlug === doc.slug ? 'page' : undefined} className={`text-sm transition-colors ${activeSlug === doc.slug ? 'text-foreground' : 'text-muted hover:text-foreground'}`}>{doc.label}</Link>)}</div></div>)}</nav></aside><section className="min-w-0">{children}</section></div></main>
}

export function DocsCard({ href, label, summary, count }: { href: string; label: string; summary: string; count?: string }) { return <Link href={href} className="group border border-line p-5 transition-colors hover:border-accent"><div className="flex items-start justify-between gap-5"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-accent">{count || 'Documentation'}</div><h2 className="mt-3 text-2xl tracking-[-.04em]">{label}</h2></div><ArrowUpRight className="size-4 text-muted transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></div><p className="mt-5 text-sm leading-6 text-muted">{summary}</p></Link> }

export function DocsArticle({ slug }: { slug: string }) { const doc = docSections.find((item) => item.slug === slug); if (!doc) return null; return <article><div className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">{doc.group} / {doc.status || 'Reference'}</div><h1 className="mt-5 max-w-4xl text-5xl leading-[.95] tracking-[-.07em] sm:text-7xl">{doc.label}</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-muted">{doc.summary}</p><div className="mt-12 grid gap-7 border-t border-line pt-8">{doc.body.map((paragraph) => <p key={paragraph} className="max-w-3xl text-base leading-8 text-foreground/80">{paragraph}</p>)}{doc.bullets && <ul className="grid gap-3 border-l-2 border-accent pl-5 text-sm leading-7 text-muted">{doc.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}</div><div className="mt-14 border-t border-line pt-6 font-mono text-[10px] uppercase tracking-[.16em] text-muted">Source discipline: current repository evidence first; supplied project specifications and documentation context second.</div></article> }
