'use client'

import Link from 'next/link'
import { ArrowUpRight, BookOpen, CircuitBoard, Globe2, Leaf, MoveUpRight, Sparkles } from 'lucide-react'
import { useEffect, useState } from 'react'
import { foundationFocus, foundationPrograms, foundationProjects, foundationValues } from '@/data/foundation'

function FoundationGraphic({ compact = false }: { compact?: boolean }) {
  return <div className={`foundation-graphic relative ${compact ? 'h-56' : 'h-[30rem] sm:h-[38rem]'}`} aria-label="An abstract system connecting knowledge, growth, technology and people" role="img">
    <div className="foundation-orbit-ring absolute left-1/2 top-1/2 aspect-square w-[78%] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[var(--foundation-cyan)]/35" />
    <div className="foundation-orbit-ring foundation-orbit-ring-two absolute left-1/2 top-1/2 aspect-square w-[58%] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[var(--foundation-orange)]/40" />
    <div className="foundation-pixel-field absolute inset-[8%] opacity-80" aria-hidden="true">{Array.from({ length: 24 }).map((_, index) => <i key={index} style={{ '--i': index } as React.CSSProperties} />)}</div>
    <svg viewBox="0 0 500 500" className="absolute inset-[8%] size-[84%] overflow-visible" fill="none" aria-hidden="true"><path d="M250 398V190M250 298L167 230M250 270l80-68M250 330l74 30M250 228l-32-54" stroke="var(--foundation-green)" strokeWidth="7" strokeLinecap="round" /><path d="M105 425Q250 380 395 425" stroke="var(--foundation-cyan)" strokeWidth="5" /><circle cx="250" cy="176" r="18" fill="var(--foundation-orange)" /><circle cx="167" cy="230" r="9" fill="var(--foundation-yellow)" /><circle cx="330" cy="202" r="9" fill="var(--foundation-cyan)" /><circle cx="324" cy="360" r="9" fill="var(--foundation-yellow)" /></svg>
    <div className="absolute left-1/2 top-[47%] flex size-28 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-[42%_58%_48%_52%] bg-[var(--foundation-surface)] text-[var(--foundation-primary)] shadow-[0_20px_70px_rgba(13,159,156,.2)] sm:size-36"><BookOpen className="size-14 sm:size-20" strokeWidth={1.2} /></div>
    <div className="absolute left-[8%] top-[13%] flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.18em] text-[var(--foundation-cyan)]"><Globe2 className="size-4" /> reach</div><div className="absolute bottom-[12%] right-[5%] flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.18em] text-[var(--foundation-green)]"><CircuitBoard className="size-4" /> possibility</div>
  </div>
}

export function FoundationExperience() {
  const [activeFocus, setActiveFocus] = useState(0)
  const [reducedMotion, setReducedMotion] = useState(false)
  useEffect(() => { const media = window.matchMedia('(prefers-reduced-motion: reduce)'); const update = () => setReducedMotion(media.matches); update(); media.addEventListener('change', update); return () => media.removeEventListener('change', update) }, [])
  return <main className="foundation-page min-h-screen overflow-hidden bg-[var(--foundation-background)] text-[var(--foundation-text)]">
    <header className="foundation-header mx-auto flex max-w-screen-2xl items-center justify-between gap-6 px-6 py-5 lg:px-10"><Link href="/" aria-label="Return to Natural Intellects"><img src="/foundation-logo.png" alt="Natural Intellects Foundation — One Life at a Time" className="h-16 w-auto object-contain sm:h-20" /></Link><nav className="hidden items-center gap-6 font-mono text-[10px] uppercase tracking-[.18em] md:flex" aria-label="Foundation navigation"><a href="#why">Why we exist</a><a href="#focus">Focus</a><a href="#deep-press">Deep Press</a><Link href="/contact" className="inline-flex items-center gap-2 border-b border-current pb-1">Contact <ArrowUpRight className="size-3" /></Link></nav><Link href="/" className="font-mono text-[10px] uppercase tracking-[.18em] md:hidden">Natural Intellects <MoveUpRight className="inline size-3" /></Link></header>
    <section className="foundation-hero mx-auto grid max-w-screen-2xl gap-8 px-6 pb-20 pt-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-10 lg:pb-28 lg:pt-20"><div className="foundation-reveal max-w-3xl"><div className="mb-7 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-primary)]"><Leaf className="size-4" /> One life at a time</div><h1 className="font-serif text-6xl leading-[.9] tracking-[-.07em] sm:text-8xl lg:text-[8.5rem]">Technology should leave people <em className="font-normal text-[var(--foundation-orange)]">stronger.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[var(--foundation-muted)]">The Foundation is a people-first expression of progress: learning, access, possibility and technology used with care.</p><div className="mt-9 flex flex-wrap items-center gap-5"><a href="#why" className="inline-flex items-center gap-3 rounded-full bg-[var(--foundation-text)] px-6 py-3 font-mono text-xs uppercase tracking-[.16em] text-[var(--foundation-background)] transition-transform hover:-translate-y-1">Follow the story <ArrowUpRight className="size-4" /></a><span className="font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-muted)]">An initiative of Natural Intellects</span></div></div><FoundationGraphic /></section>
    <section id="why" className="foundation-story border-y border-[var(--foundation-text)]/15 bg-[var(--foundation-surface)] px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-screen-2xl gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-orange)]">Why we exist</div><h2 className="mt-5 max-w-md font-serif text-5xl leading-none tracking-[-.06em] sm:text-7xl">One opportunity can change the shape of a life.</h2></div><div className="max-w-2xl"><p className="text-2xl leading-relaxed text-[var(--foundation-muted)]">We believe technology is most meaningful when it expands participation, strengthens confidence and leaves people with more agency than they started with.</p><div className="foundation-path mt-12 grid gap-4 border-t border-[var(--foundation-text)]/20 pt-8 sm:grid-cols-4">{['Knowledge','Growth','People','Opportunity'].map((item, index) => <div key={item} className="relative"><span className="mb-4 flex size-10 items-center justify-center rounded-full border border-[var(--foundation-primary)] font-mono text-xs text-[var(--foundation-primary)]">0{index + 1}</span><div className="font-serif text-xl">{item}</div></div>)}</div></div></div></section>
    <section id="focus" className="mx-auto max-w-screen-2xl px-6 py-20 lg:px-10 lg:py-32"><div className="mb-12 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-orange)]">Our focus</div><h2 className="mt-5 font-serif text-5xl leading-none tracking-[-.06em] sm:text-7xl">Open doors, not boxes.</h2></div><p className="max-w-xs text-sm leading-6 text-[var(--foundation-muted)]">Explore the areas where learning, access and responsible innovation meet.</p></div><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="relative"><FoundationGraphic compact /><div className="absolute inset-0 flex items-center justify-center"><Sparkles className="size-8 text-[var(--foundation-orange)]" /></div></div><div className="border-t border-[var(--foundation-text)]/20">{foundationFocus.map((item, index) => <button key={item.number} type="button" onClick={() => setActiveFocus(index)} className={`foundation-focus-item flex w-full items-start gap-5 border-b border-[var(--foundation-text)]/20 py-6 text-left transition-colors ${activeFocus === index ? 'text-[var(--foundation-primary)]' : 'text-[var(--foundation-text)] hover:text-[var(--foundation-cyan)]'}`} aria-pressed={activeFocus === index}><span className="font-mono text-xs">{item.number}</span><span><strong className="font-serif text-3xl font-normal">{item.title}</strong><span className={`mt-3 block max-w-xl text-sm leading-6 text-[var(--foundation-muted)] transition-all ${activeFocus === index ? 'max-h-24 opacity-100' : 'max-h-0 overflow-hidden opacity-0'}`}>{item.description}</span></span></button>)}</div></div></section>
    <section id="deep-press" className="bg-[var(--foundation-text)] px-6 py-20 text-[var(--foundation-background)] lg:px-10 lg:py-28"><div className="mx-auto grid max-w-screen-2xl gap-12 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-yellow)]">{foundationProjects.deepPress.name} / Foundation initiative / {foundationProjects.deepPress.status}</div><h2 className="mt-5 max-w-2xl font-serif text-5xl leading-none tracking-[-.06em] sm:text-7xl">A Foundation initiative for somewhere to begin.</h2><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--foundation-surface)]/75">{foundationProjects.deepPress.shortDescription}</p><Link href={foundationProjects.deepPress.route} className="mt-8 inline-flex items-center gap-2 border-b border-[var(--foundation-yellow)] pb-2 font-mono text-xs uppercase tracking-[.16em] text-[var(--foundation-yellow)]">Explore Deep Press <ArrowUpRight className="size-4" /></Link></div><div className="deep-press-visual relative flex min-h-72 items-center justify-center overflow-hidden rounded-[2rem] border border-[var(--foundation-cyan)]/25 bg-[var(--foundation-primary)]/15"><div className="deep-press-wave absolute size-44 rounded-full border border-[var(--foundation-cyan)]/60 sm:size-64" /><div className="deep-press-wave absolute size-28 rounded-full border border-[var(--foundation-yellow)]/50 sm:size-40" /><div className="size-5 rounded-full bg-[var(--foundation-yellow)] shadow-[0_0_50px_var(--foundation-yellow)]" /><span className="absolute bottom-6 left-6 font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-surface)]/70">connection / space / support</span></div></div></section>
    <section className="foundation-one-life px-6 py-24 lg:px-10 lg:py-36"><div className="mx-auto max-w-screen-2xl text-center"><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-orange)]">The measure is human</div><h2 className="mt-8 font-serif text-6xl leading-[.85] tracking-[-.08em] sm:text-9xl">One Life<br /><em className="font-normal text-[var(--foundation-primary)]">at a Time.</em></h2><div className="mx-auto mt-10 flex max-w-xl items-center justify-center gap-3 font-mono text-[10px] uppercase tracking-[.2em] text-[var(--foundation-muted)]"><span className="h-px flex-1 bg-[var(--foundation-primary)]/30" />one → possibility → impact<span className="h-px flex-1 bg-[var(--foundation-primary)]/30" /></div></div></section>
    <section className="border-t border-[var(--foundation-text)]/15 px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-screen-2xl gap-10 lg:grid-cols-[1fr_.8fr]"><div><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[var(--foundation-orange)]">How we show up</div><h2 className="mt-5 max-w-2xl font-serif text-5xl leading-none tracking-[-.06em] sm:text-7xl">Keep the door open.</h2></div><ul className="border-t border-[var(--foundation-text)]/20">{foundationValues.map((value, index) => <li key={value} className="flex items-center gap-5 border-b border-[var(--foundation-text)]/20 py-5"><span className="font-mono text-xs text-[var(--foundation-orange)]">0{index + 1}</span><span className="font-serif text-2xl">{value}</span></li>)}</ul></div></section>
    <footer className="border-t border-[var(--foundation-text)]/15 px-6 py-8 lg:px-10"><div className="mx-auto flex max-w-screen-2xl flex-col justify-between gap-4 sm:flex-row"><div className="flex items-center gap-4"><img src="/foundation-logo.png" alt="Natural Intellects Foundation" className="h-14 w-auto object-contain" /><span className="font-serif text-lg italic">One Life at a Time.</span></div><div className="flex items-center gap-5 font-mono text-[10px] uppercase tracking-[.18em] text-[var(--foundation-muted)]"><Link href="/" className="hover:text-[var(--foundation-orange)]">Natural Intellects</Link><Link href="/contact" className="hover:text-[var(--foundation-orange)]">Talk with us</Link></div></div></footer>
  </main>
}
